junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.classes.default = concurrent

# Opt in to the new executor
junit.jupiter.execution.parallel.config.executor-service=WORKER_THREAD_POOL

# If we parallelize at the method level, we seem to end up overloading databases
# and causing timeouts due to our deliberately short timeout settings.
junit.jupiter.execution.parallel.mode.default = same_thread

# Way longer than tests should actually take; 5s would probably work
junit.jupiter.execution.timeout.default=1m
