# Based on:
# - https://github.com/assertj/assertj/blob/f08f94806675ccaaa347e4cbc56cf02efa8cd3be/.github/workflows/release.yml#L1
# - https://github.com/testcontainers/testcontainers-java/blob/de20484e53eb8d1f580b74ff9df31261b596ab5c/.github/workflows/release.yml#L1
# - https://github.com/gradle/gradle-build-action#caching

name: "Build and test"

on: [push]

jobs:
  build_and_test:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: temurin

      - name: Run Gradle Test
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: wrapper
          arguments: spotlessCheck spotBugsMain test
        env:
          ORG_GRADLE_PROJECT_ossrhUsername: ${{secrets.OSSRH_USERNAME}}
          ORG_GRADLE_PROJECT_ossrhPassword: ${{secrets.OSSRH_TOKEN}}
          ORG_GRADLE_PROJECT_signingKey: ${{secrets.GPG_PRIVATE_KEY}}
          ORG_GRADLE_PROJECT_signingPassword: ${{secrets.GPG_PASSWORD}}
