name: Sync Docs

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 25
      - uses: gradle/actions/setup-gradle@v6

      - name: Sync javadoc.io
        run: |
          LIBRARIES=$(./gradlew listPublishedLibraries -q --console=plain)
          for lib in $LIBRARIES; do
            lib_path="${lib//://}"
            curl -s -o /dev/null -w "%{http_code} - $lib\n" "https://javadoc.io/task/sync_latest/$lib_path"
          done
